-- MySQL Script generated by MySQL Workbench
-- Thu Mar  7 05:45:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id8539685_knjizara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id8539685_knjizara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id8539685_knjizara` DEFAULT CHARACTER SET latin2 ;
USE `id8539685_knjizara` ;

-- -----------------------------------------------------
-- Table `id8539685_knjizara`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id8539685_knjizara`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `id8539685_knjizara`.`korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `starost` INT NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id8539685_knjizara`.`knjiga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id8539685_knjizara`.`knjiga` ;

CREATE TABLE IF NOT EXISTS `id8539685_knjizara`.`knjiga` (
  `idknjiga` INT NOT NULL AUTO_INCREMENT,
  `naslov` VARCHAR(45) NOT NULL,
  `pisac` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `brojStranica` INT NOT NULL,
  `cijena` FLOAT(6,2) NOT NULL,
  `sadrzaj` MEDIUMTEXT NOT NULL,
  `slika` VARCHAR(240) NOT NULL,
  PRIMARY KEY (`idknjiga`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id8539685_knjizara`.`racun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id8539685_knjizara`.`racun` ;

CREATE TABLE IF NOT EXISTS `id8539685_knjizara`.`racun` (
  `idracun` INT NOT NULL AUTO_INCREMENT,
  `ukupnaCijena` FLOAT NOT NULL,
  `brojKupljenihKnjiga` INT NOT NULL,
  PRIMARY KEY (`idracun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id8539685_knjizara`.`kategorija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id8539685_knjizara`.`kategorija` ;

CREATE TABLE IF NOT EXISTS `id8539685_knjizara`.`kategorija` (
  `idkategorija` INT NOT NULL AUTO_INCREMENT,
  `nazivKategorije` VARCHAR(45) NOT NULL,
  `knjiga_idknjiga` INT NOT NULL,
  PRIMARY KEY (`idkategorija`, `knjiga_idknjiga`),
  INDEX `fk_kategorija_knjiga1_idx` (`knjiga_idknjiga` ASC),
  CONSTRAINT `fk_kategorija_knjiga1`
    FOREIGN KEY (`knjiga_idknjiga`)
    REFERENCES `id8539685_knjizara`.`knjiga` (`idknjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id8539685_knjizara`.`komentar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id8539685_knjizara`.`komentar` ;

CREATE TABLE IF NOT EXISTS `id8539685_knjizara`.`komentar` (
  `idkomentar` INT NOT NULL AUTO_INCREMENT,
  `datum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `knjiga_idknjiga` INT NOT NULL,
  `korisnik_idKorisnik` INT NOT NULL,
  `sadrzajKomentara` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idkomentar`, `knjiga_idknjiga`, `korisnik_idKorisnik`),
  INDEX `fk_komentar_knjiga1_idx` (`knjiga_idknjiga` ASC),
  INDEX `fk_komentar_korisnik1_idx` (`korisnik_idKorisnik` ASC),
  CONSTRAINT `fk_komentar_knjiga1`
    FOREIGN KEY (`knjiga_idknjiga`)
    REFERENCES `id8539685_knjizara`.`knjiga` (`idknjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_komentar_korisnik1`
    FOREIGN KEY (`korisnik_idKorisnik`)
    REFERENCES `id8539685_knjizara`.`korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `id8539685_knjizara`.`korisnik`
-- -----------------------------------------------------
START TRANSACTION;
USE `id8539685_knjizara`;
INSERT INTO `id8539685_knjizara`.`korisnik` (`idKorisnik`, `ime`, `prezime`, `starost`, `email`, `lozinka`) VALUES (1, 'Ana', 'Anić', 25, 'ana@gmail.com', 'ana123');
INSERT INTO `id8539685_knjizara`.`korisnik` (`idKorisnik`, `ime`, `prezime`, `starost`, `email`, `lozinka`) VALUES (2, 'Marija', 'Marić', 27, 'marija@gmail.com', 'marija123');
INSERT INTO `id8539685_knjizara`.`korisnik` (`idKorisnik`, `ime`, `prezime`, `starost`, `email`, `lozinka`) VALUES (3, 'Sanja', 'Sanjić', 22, 'sanja@gmail.com', 'sanja123');
INSERT INTO `id8539685_knjizara`.`korisnik` (`idKorisnik`, `ime`, `prezime`, `starost`, `email`, `lozinka`) VALUES (4, 'Ruzica', 'Vučemil', 23, 'ruzicavucemil@gmail.com', 'ruzica123');
INSERT INTO `id8539685_knjizara`.`korisnik` (`idKorisnik`, `ime`, `prezime`, `starost`, `email`, `lozinka`) VALUES (5, 'admin', 'admin', 99, 'admin@gmail.com', 'admin123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `id8539685_knjizara`.`knjiga`
-- -----------------------------------------------------
START TRANSACTION;
USE `id8539685_knjizara`;
INSERT INTO `id8539685_knjizara`.`knjiga` (`idknjiga`, `naslov`, `pisac`, `isbn`, `brojStranica`, `cijena`, `sadrzaj`, `slika`) VALUES (1, 'Zločin i Kazna', 'Fjodor Mihajlovič Dostojevski', '978-953-0-60191-8', 828, 45.50, 'Koristeći kriminalističku priču Dostojevski je sastavio roman kojim je predočio svu složenost u odnosu pojedinca prema postojećim zakonima. Brze društvene mijene u cijeloj Europi 19. stoljeća, a posebice u Rusiji, dovode do velikih socijalnih nepravda. Pojedinac se tako našao u procjepu između zakona, kojim se zaštićuje, i nepravda, te potrebe da se sačuvaju ljudske vrijednosti. Dostojevski je upravo tome posvetio svoje velike priče.', 'zlocin_i_kazna.jpg');
INSERT INTO `id8539685_knjizara`.`knjiga` (`idknjiga`, `naslov`, `pisac`, `isbn`, `brojStranica`, `cijena`, `sadrzaj`, `slika`) VALUES (2, 'Ana Karenjina', 'Lav Tolstoj', '978-9958-27-289-9', 815, 30.00, 'Osveta je moja i ja ću je vratiti.', 'ana_karenjina.jpg');
INSERT INTO `id8539685_knjizara`.`knjiga` (`idknjiga`, `naslov`, `pisac`, `isbn`, `brojStranica`, `cijena`, `sadrzaj`, `slika`) VALUES (3, 'Starac i More', 'Ernest Hemnigway', '9788689203769', 104, 12.00, 'Starac i more je verovatno najpoznatiji roman najpoznatijeg pisca na svetu. Priča o ribaru sa Kube koji se tokom tri dana bori sa silama prirode da preživi na otvorenom moru. Ali i sa svojom ljudskom naravi koja, sačinjena od slabosti, ponosa, strahova i svesti o svojoj krhkoj prirodi, može veoma lako postati i glavni protivnik u borbi za život.', 'starac_i_more.jpg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `id8539685_knjizara`.`racun`
-- -----------------------------------------------------
START TRANSACTION;
USE `id8539685_knjizara`;
INSERT INTO `id8539685_knjizara`.`racun` (`idracun`, `ukupnaCijena`, `brojKupljenihKnjiga`) VALUES (1, 60.00, 2);
INSERT INTO `id8539685_knjizara`.`racun` (`idracun`, `ukupnaCijena`, `brojKupljenihKnjiga`) VALUES (2, 90.00, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `id8539685_knjizara`.`kategorija`
-- -----------------------------------------------------
START TRANSACTION;
USE `id8539685_knjizara`;
INSERT INTO `id8539685_knjizara`.`kategorija` (`idkategorija`, `nazivKategorije`, `knjiga_idknjiga`) VALUES (1, 'Klasika', 2);
INSERT INTO `id8539685_knjizara`.`kategorija` (`idkategorija`, `nazivKategorije`, `knjiga_idknjiga`) VALUES (2, 'Poezija', 1);
INSERT INTO `id8539685_knjizara`.`kategorija` (`idkategorija`, `nazivKategorije`, `knjiga_idknjiga`) VALUES (3, 'Klasika', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `id8539685_knjizara`.`komentar`
-- -----------------------------------------------------
START TRANSACTION;
USE `id8539685_knjizara`;
INSERT INTO `id8539685_knjizara`.`komentar` (`idkomentar`, `datum`, `knjiga_idknjiga`, `korisnik_idKorisnik`, `sadrzajKomentara`) VALUES (1, DEFAULT, 1, 2, 'Ova knjiga je remek dijelo.');
INSERT INTO `id8539685_knjizara`.`komentar` (`idkomentar`, `datum`, `knjiga_idknjiga`, `korisnik_idKorisnik`, `sadrzajKomentara`) VALUES (2, DEFAULT, 1, 1, 'Slažem se sa vama.');
INSERT INTO `id8539685_knjizara`.`komentar` (`idkomentar`, `datum`, `knjiga_idknjiga`, `korisnik_idKorisnik`, `sadrzajKomentara`) VALUES (3, DEFAULT, 2, 1, 'Inspirirajuća knjiga.');

COMMIT;

